{{- if .Values.rbac.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.initServiceAccountName }}
  labels:
{{ include "sidecar-injector-init.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get"]
{{- end }}
