{{- if .Values.rbac.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.initServiceAccountName }}
  labels:
{{ include "sidecar-injector-init.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.initServiceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.initServiceAccountName }}
{{- end }}