apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{.Release.Name}}
  labels:
{{ include "sidecar-injector.labels" . | indent 4 }}
webhooks:
  - name: com.cloudbees.sidecar-injector
    clientConfig:
      service:
        name: {{ .Values.serviceName }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
      caBundle: ""
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
{{- if .Values.enableNamespacesByDefault }}
      matchExpressions:
      - key: name
        operator: NotIn
        values:
        - {{ .Release.Namespace }}
      - key: {{ .Values.namespaceLabel }}
        operator: NotIn
        values:
        - disabled
{{- else }}
      matchLabels:
        {{ .Values.namespaceLabel }}: enabled
{{- end }}

